/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "pc.h"
#include <sys/sem.h>
#include <sys/stat.h>

#define binary 0
#define bempty 1
#define bfull 2
struct sembuf start_prod[2] = {{bempty, -1, SEM_UNDO}, {binary, -1, SEM_UNDO}};
struct sembuf end_prod[2] = {{binary, 1, SEM_UNDO}, {bfull, 1, SEM_UNDO}};
struct sembuf start_cons[2] = {{bfull, -1, SEM_UNDO}, {binary, -1, SEM_UNDO}};
struct sembuf stop_cons[2] = {{binary, 1, SEM_UNDO}, {bempty, 1, SEM_UNDO}};

#define size_buf 1000
char *buf, *cons_ptr, *prod_ptr, alpha;
int semid;

bool_t
consumer_1_svc(void *argp, char *result, struct svc_req *rqstp)
{
	if (semop(semid, start_cons, 2) == -1) {
		perror("semop");
		exit(1);
	}
	*result = *cons_ptr;
	cons_ptr++;
	if (cons_ptr - buf == size_buf)
		cons_ptr = buf;
	if (semop(semid, stop_cons, 2) == -1) {
		perror("semop");
		exit(1);
	}
	return TRUE;
}

bool_t
producer_1_svc(void *argp, char *result, struct svc_req *rqstp)
{
	if (semop(semid, start_prod, 2) == -1) {
		perror("semop");
		exit(1);
	}
	*prod_ptr = alpha;
	*result = alpha;
	if (alpha == 'z')
		alpha = 'a';
	else
		alpha++;
	prod_ptr++;
	if (prod_ptr - buf == size_buf)
		prod_ptr = buf;
	if (semop(semid, end_prod, 2) == -1) {
		perror("semop");
		exit(1);
	}

	return TRUE;
}

int
pc_prog_1_freeresult (SVCXPRT *transp, xdrproc_t xdr_result, caddr_t result)
{
	xdr_free (xdr_result, result);

	/*
	 * Insert additional freeing code here, if needed
	 */

	return 1;
}

int pc_init() {
	buf = malloc(sizeof(char) * size_buf);
	if (buf == NULL) {
		perror('malloc');
		return -1;
	}
	cons_ptr = buf;
	prod_ptr = buf;
	alpha = 'a';

	int perms = S_IRUSR | S_IWUSR | S_IRGRP | S_IROTH;
    semid = semget(IPC_PRIVATE, 3, IPC_CREAT | perms);
    if (semid == -1) {
		perror("semget");
		return -1;
	}
	if (semctl(semid, binary, SETVAL, 1) == -1) {
        perror("semctl"); 
        return -1;
    }
    if (semctl(semid, bempty, SETVAL, size_buf) == -1) {
        perror("semctl"); 
        return -1;
    }
    if (semctl(semid, bfull, SETVAL, 0) == -1) {
        perror("semctl"); 
        return -1;
    }
	return 0;
}