/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "pc.h"
#define max_time_sleep 3

void
pc_prog_consumer(char *host) {
	CLIENT *clnt;
	enum clnt_stat retval_1;
	char result_1;
	char *consumer_1_arg = NULL;

#ifndef	DEBUG
	clnt = clnt_create (host, PC_PROG, PC_VER, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	srand(getpid());
	while (1) {
		sleep(rand() % (max_time_sleep + 1));
		retval_1 = producer_1((void*)&consumer_1_arg, &result_1, clnt);
		if (retval_1 != RPC_SUCCESS) {
			clnt_perror (clnt, "call failed");
		}
		printf("Потребитель   PID=%d взял    '%c'\n", getpid(), result_1);
	}
	
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */

	retval_1 = consumer_1((void*)&consumer_1_arg, &result_1, clnt);
	if (retval_1 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
}

void
pc_prog_producer(char *host)
{
	CLIENT *clnt;
	enum clnt_stat retval_2;
	char result_2;
	char *producer_1_arg = NULL;

#ifndef	DEBUG
	clnt = clnt_create (host, PC_PROG, PC_VER, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	srand(getpid());
	while (1) {
		sleep(rand() % (max_time_sleep + 1));
		retval_2 = producer_1((void*)&producer_1_arg, &result_2, clnt);
		if (retval_2 != RPC_SUCCESS) {
			clnt_perror (clnt, "call failed");
		}
		printf("Производитель PID=%d положил '%c'\n", getpid(), result_2);
	}
	
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 3) {
		printf ("usage: %s server_host type_pc\n", argv[0]);
		printf ("producer: type_pc=1\n");
		printf ("consumer: type_pc=2\n");
		exit (1);
	}
	host = argv[1];
	if (strcmp(argv[2], "1") == 0) {
		pc_prog_1 (host);
	} else if (strcmp(argv[2], "2") == 0) {
		pc_prog_1 (host);
	} else {
		printf ("usage: %s server_host type_pc\n", argv[0]);
		printf ("producer: type_pc=1\n");
		printf ("consumer: type_pc=2\n");
		exit (1);
	}
	exit (0);
}
