/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "bakery.h"


void
bakery_prog_1(char *host, int ind)
{
	CLIENT *clnt;
	enum clnt_stat retval_1;
	struct BAKERY result_1;
	struct BAKERY  request;
	enum clnt_stat retval_2;
	struct BAKERY result_2;

#ifndef	DEBUG
	clnt = clnt_create (host, BAKERY_PROG, BAKERY_VER, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	srand(time(NULL));
	request.pid = getpid();
	request.ind = ind;
	request.op = 0;
	request.arg1 = 2;
	request.arg2 = 3;

	retval_1 = get_number_1(&request, &result_1, clnt);
	if (retval_1 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	request.num = result_1.num;

	printf("PID=%d num=%d ind=%d\n", request.pid, request.num, request.ind);
	usleep(350 *ind);
	// retval_2 = serve_1(&request, &result_2, clnt);
	// if (retval_2 != RPC_SUCCESS) {
	// 	clnt_perror (clnt, "call failed");
	// }
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	pid_t client_pid[COUNT_CLIENTS];

	for (size_t i = 0; i < COUNT_CLIENTS; i++)
	{
		if ((client_pid[i] = fork()) == -1)
		{
			perror("Can't fork\n");
			exit(1);
		}
		else if (client_pid[i] == 0)
		{
			bakery_prog_1(host, i);
			return 0;
		}
	}
	printf("created: ");
	for (size_t i = 0; i < COUNT_CLIENTS; i++)
		printf("%d ", client_pid[i]);
	printf("\n");

	int wstatus;
	pid_t w;
	for (size_t i = 0; i < COUNT_CLIENTS; i++)
	{
		w = waitpid(-1, &wstatus, 0); // until one of its children terminates (ANY child process.)
        if (w == -1) {
            char err_msg[100];
            sprintf(err_msg, "ERR: waitpid PID=%d, errno=%d", getpid(), errno);
            perror(err_msg);
			exit(EXIT_FAILURE);
        }

        printf("PID=%d ", w);
        if (WIFEXITED(wstatus)) {                                    
            printf("exited, status = %d ", WEXITSTATUS(wstatus));
        } else if (WIFSIGNALED(wstatus)) {
            printf("killed by signal %d ", WTERMSIG(wstatus));
        }
        printf("\n");
	}

	printf("Parent client exited\n");
exit (0);
}
