/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _BAKERY_H_RPCGEN
#define _BAKERY_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#include <unistd.h>
#include <sys/wait.h>
#include <errno.h>
#define COUNT_CLIENTS 5
static pthread_mutex_t mut[COUNT_CLIENTS];


#ifdef __cplusplus
extern "C" {
#endif

#define ADD 0
#define SUB 1
#define MUL 2
#define DIV 3

struct BAKERY {
	int num;
	int pid;
	int ind;
	int op;
	float arg1;
	float arg2;
	int result;
};
typedef struct BAKERY BAKERY;


#define BAKERY_PROG 0x20000001
#define BAKERY_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define GET_NUMBER 1
extern  enum clnt_stat get_number_1(struct BAKERY *, struct BAKERY *, CLIENT *);
extern  bool_t get_number_1_svc(struct BAKERY *, struct BAKERY *, struct svc_req *);
#define SERVE 2
extern  enum clnt_stat serve_1(struct BAKERY *, struct BAKERY *, CLIENT *);
extern  bool_t serve_1_svc(struct BAKERY *, struct BAKERY *, struct svc_req *);
extern int bakery_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define GET_NUMBER 1
extern  enum clnt_stat get_number_1();
extern  bool_t get_number_1_svc();
#define SERVE 2
extern  enum clnt_stat serve_1();
extern  bool_t serve_1_svc();
extern int bakery_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_BAKERY (XDR *, BAKERY*);

#else /* K&R C */
extern bool_t xdr_BAKERY ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_BAKERY_H_RPCGEN */
