/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "bakery.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
get_number_1(struct BAKERY *argp, struct BAKERY *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, GET_NUMBER,
		(xdrproc_t) xdr_BAKERY, (caddr_t) argp,
		(xdrproc_t) xdr_BAKERY, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
serve_1(struct BAKERY *argp, struct BAKERY *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, SERVE,
		(xdrproc_t) xdr_BAKERY, (caddr_t) argp,
		(xdrproc_t) xdr_BAKERY, (caddr_t) clnt_res,
		TIMEOUT));
}
