/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "bakery.h"

#define CLIENTS_COUNT 5

void
bakery_prog_1(char *host)
{
	CLIENT *clnt;
	enum clnt_stat retval_1;
	struct BAKERY result_1;
	struct BAKERY  get_number_1_arg;
	enum clnt_stat retval_2;
	struct BAKERY result_2;
	struct BAKERY  serve_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, BAKERY_PROG, BAKERY_VER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	retval_1 = get_number_1(&get_number_1_arg, &result_1, clnt);
	if (retval_1 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_2 = serve_1(&serve_1_arg, &result_2, clnt);
	if (retval_2 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	bakery_prog_1 (host);

	pid_t client_pid[CLIENTS_COUNT];

	for (size_t i = 0; i < CLIENTS_COUNT; i++)
	{
		if ((client_pid[i] = fork()) == -1)
		{
			perror("Can't fork\n");
			exit(1);
		}
		else if (client_pid[i] == 0)
		{
			bakery_prog_1(host);
			return 0;
		}
	}

	for (size_t i = 0; i < CLIENTS_COUNT; i++)
	{
		int status;
		waitpid(client_pid[i], &status, 0);
	}

	printf("Parent client exited\n");
exit (0);
}
