/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "pc.h"
#define max_time_sleep 4

void
pc_prog_1(char *host, char type)
{
	CLIENT *clnt;
	enum clnt_stat retval_1;
	char result_1;
	int  producer_1_arg;
	enum clnt_stat retval_2;
	char result_2;
	int  consumer_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, PC_PROG, PC_VER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	srand(time(NULL));
	if (type == 'p') {
		producer_1_arg = getpid();
		while (1) {
			sleep(rand() % max_time_sleep + 1);
			retval_1 = producer_1(&producer_1_arg, &result_1, clnt);
			if (retval_1 != RPC_SUCCESS) {
				char * es = clnt_sperrno(retval_1);
				printf("%s\n", es);
				// clnt_perror (clnt, "call failed");
			}
			printf("Производитель PID=%d положил '%c'\n", getpid(), result_1);
		}
	} else if (type == 'c') {
		consumer_1_arg = getpid();
		while (1) {
			sleep(rand() % max_time_sleep + 1);
			retval_2 = consumer_1(&consumer_1_arg, &result_2, clnt);
			if (retval_2 != RPC_SUCCESS) {
				char * es = clnt_sperrno(retval_2);
				printf("%s\n", es);
				// clnt_perror (clnt, "call failed");
			}
			printf("Потребитель   PID=%d взял    '%c'\n", getpid(), result_2);
		}

	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	char type;
	if (argc < 3) {
		printf ("usage: %s server_host type\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	type = *(argv[2]);
	if (type != 'p' && type != 'c') {
		printf ("error type, must be 'p' or 'c'\n");
		exit(1);
    }
	pc_prog_1 (host, type);
	exit (0);
}
