/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "bakery.h"


void
bakery_prog_1(char *host)
{
	CLIENT *clnt;

#ifndef	DEBUG
	clnt = clnt_create (host, BAKERY_PROG, BAKERY_VER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	srand(getpid());
	while (1) {
		struct BAKERY  *result_1;
		struct BAKERY  request;
		struct BAKERY  *result_2;
		sleep(rand() % 4);
		request.pid = getpid();
		request.op = rand() % 4;
		request.arg1 = rand() % 10;
		request.arg2 = rand() % 10;

		result_1 = get_number_1(&request, clnt);
		if (result_1 == (struct BAKERY *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		if (result_1->num == -1) {
			printf("Error: no free numbers\n");
			exit(EXIT_FAILURE);
		}
		// printf("PID=%d get num=%d\n", request.pid, result_1->num);

		sleep(rand() % 4);
		request.num = result_1->num;
		result_2 = serve_1(&request, clnt);
		if (result_2 == (struct BAKERY *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		if (result_2->num == -1) {
			printf("Error: late\n");
		} else {
			char *op;
			switch(request.op)
			{
				case ADD:
					op = "add";
					break;
				case SUB:
					op = "sub";
					break;
				case MUL:
					op = "mul";
					break;
				case DIV:
					op = "div";
					break;
				default:
					break;
			}
			printf("PID=%d num=%d, %lf (%s) %lf = %lf\n", request.pid, result_1->num, request.arg1, op, request.arg2, result_2->result);
		}
	}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	bakery_prog_1(host);
exit (0);
}
