/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "bakery.h"

static int numbers[COUNT_CLIENTS] = {0};
static int pids[COUNT_CLIENTS] = {0};
pthread_mutex_t mutex = PTHREAD_MUTEX_INITIALIZER;

int max_number()
{
	int res = numbers[0];

	for (int i = 0; i < COUNT_CLIENTS; i++)
		if (numbers[i] > res)
			res = numbers[i];

	return res;
}

struct BAKERY *
get_number_1_svc(struct BAKERY *argp, struct svc_req *rqstp)
{
	static struct BAKERY  result;

	pthread_mutex_lock(&mutex);
	result.num = max_number() + 1;
	numbers[argp->ind] = result.num;

	printf("numders: ");
	for (int i = 0; i < COUNT_CLIENTS; i++)
		printf("%d ", numbers[i]);
	printf("\n");
	pthread_mutex_unlock(&mutex);
	return &result;
}

struct BAKERY *
serve_1_svc(struct BAKERY *argp, struct svc_req *rqstp)
{
	static struct BAKERY  result;
	switch(argp->op)
	{
		case ADD:
			result.result = argp->arg1 + argp->arg2;
			break;
		case SUB:
			result.result = argp->arg1 - argp->arg2;
			break;
		case MUL:
			result.result = argp->arg1 * argp->arg2;
			break;
		case DIV:
			result.result = argp->arg1 / argp->arg2;
			break;
		default:
			break;
	}

	return &result;
}
