/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <stdlib.h>
#include <stdio.h>
#include <time.h>
#include <unistd.h>
#include "pc.h"

void pc_prog_1(char *host, int role)
{
	CLIENT *clnt;
	enum clnt_stat retval_1;
	char result_1;
	int  service_1_arg = role;

#ifndef	DEBUG
	clnt = clnt_create (host, PC_PROG, PC_VER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	srand(time(NULL));
	while (1)
	{
		if (service_1_arg == 0) 
			sleep(rand() % 3 + 1);
		else 
			sleep(rand() % 4 + 1);

		retval_1 = service_1(&service_1_arg, &result_1, clnt);
    	if (retval_1 != RPC_SUCCESS) {
			clnt_perror(clnt, "call failed");
			break;
		} else
		{
			if (service_1_arg == 0) 
				printf("Producer put %c\n", result_1);
			else 
				printf("Consumer get %c\n", result_1);
		}
    }
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int main (int argc, char *argv[])
{
	char *host;
	char role;
	if (argc < 3) {
		printf ("usage: %s server_host role\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	role = *argv[2];
	if (role == 'p')
		pc_prog_1(host, 0);
	else if (role == 'c')
		pc_prog_1(host, 1);
    else {
        printf("role must be p or c\n");
        exit(1);
    }

    pc_prog_1(host, role);
exit (0);
}
