/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PC_H_RPCGEN
#define _PC_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


#define PRODUCER_CONSUMER_PROGRAM 0x20000001
#define PRODUCER_CONSUMER_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define PRODUCE 1
extern  enum clnt_stat produce_1(int *, char *, CLIENT *);
extern  bool_t produce_1_svc(int *, char *, struct svc_req *);
#define CONSUME 2
extern  enum clnt_stat consume_1(int *, char *, CLIENT *);
extern  bool_t consume_1_svc(int *, char *, struct svc_req *);
extern int producer_consumer_program_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define PRODUCE 1
extern  enum clnt_stat produce_1();
extern  bool_t produce_1_svc();
#define CONSUME 2
extern  enum clnt_stat consume_1();
extern  bool_t consume_1_svc();
extern int producer_consumer_program_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#define BUFF_SIZE 1024

#endif /* !_PC_H_RPCGEN */
